### ISSUE TITLE
Repository memberships should be tracked outside of the tools repo

### ISSUE THREAD

**Issue by joostschriek** [joostschriek/gitman#11]
To make this tool actually general use, this repository collaborator information should be contained in its own file much like teams.json.

This data should be able to communicate;

- What access the team has to which repos.
  - Defaults to `write`
- In or exclusion based on repo lists
  - the `only` and `not` filters that exist in the code right now.

A simpler option could be to specify a control structure, and just serialize this to JSON (like the current `teams.json`) The downside being that it could get very large very quick. 

```csharp
public class Control {
    public class TeamDescription { 
        public string Repo { .. };
        public string Not { .. }; 
        public string Only { .. }; 
        public GithubPermission Permission = GithubPermission.Write;
    }

    public IDictioary<string, IEnum<string>> RepoLists;
    public IEnum<TeamDescription> TeamDescriptions;
}
```

```json
repos.json
{
    "admins": {
        "permission": "admin"
    },
    "team-admins": {
        "permission": "admin",
        "only": "admin_repos"
    },
    "developers": {
        "not": "admin_repos",
    }
}

teams.json
{
    "admins": [ ... ],
    "team-admins": [ ... ],
    "developers": [ ... ]
}
```

If we want to keep this k8s manifest adjacent (since that is most of our code), we could opt for a YAML thing where we specify `kind` and `spec`.  This requires a bit more work upfront but would allow us to use tools like kustomzie to just zip everything up. 

```yaml
kind: RepoList
metadata:
    name: admin-repos
spec:
    - "gutcheck"
    - "some-other-repos"
--- 
kind: TeamDescription
metadata:
    name: admin-description
spec:
    teamname: "admin"
    permissionlevel: "admin"
---
kind: TeamDescription
metadata:
    name: developer-description
spec:
    teamname: "developers"
    not:
        listRef:
            name: admin-repos
---
kind: TeamDescription
metadata:
    name: developer-admin-repos-description
spec:
    teamname: "developers"
    permission: read
    only:
        listRef:
            name: admin-repos
```

```csharp
using System;
using System.Collections.Generic;

public class Base {
    public class Meta {
        public string Name { get; set; }
    }

    public string apiVersion { get; set; } = "git.amanagement.v1";
    public string Kind { get; set; }
    public Meta Metadata {get; set; }
}

public class BaseResource<T> : Base {
    public T Spec { get; set; }
}

public class RepoListResource : BaseResource<List<string>> {
    public RepoListResource() {
        // The kind here is almost pointless but mostly for documentation purposes.
        Kind = "RepoList";
    }
}


public class TeamDescription {
    public string Name { get; set; }
    public string PermissionLevel { get; set; }
    public List<string> Only { get; set; }
    public List<string> Not { get; set; }
}

public class TeamDescriptionResource : BaseResource<TeamDescription> {
    public TeamDescriptionResource() {
        // The kind here is almost pointless but mostly for documentation purposes.
        Kind = "TeamDescription";
    }
}
```

We would have to deserialize these types of structures, and then process the values. This is basically what a k8s operator is doing.
